name: deploy-container

on: 
 push: 
   branches:
     - master
   paths: #path indicates that we will only run where there is change in the container dir
     - 'packages/container/**'

defaults: 
  run: 
    working-directory: packages/container #chnage into the container folder

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
       - uses: actions/checkout@v2
       - run: npm install
       - run: npm run build

       - uses: shinyinc/action-aws-cli@v1.2
       - run: aws s3 cp dist --region ca-central-1 $ARCHIVE_NAME s3://${{ secrets.AWS_S3_BUCKET_NAME }}//container/latest
         env: 
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}